name: Publish

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      message:
        description: 'Commit message'
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - name: Checkout this repo
      uses: actions/checkout@v3
      with:
        ref: gh-pages
        path: dist
    - name: Checkout web client repo
      uses: actions/checkout@v3
      with:
        repository: picapica-org/picapica-web-client
        ref: main
        path: client
    - name: Build client
      run: cd client && npm ci && npm run build
      env:
        CI: true
    - name: Clean dist
      run: cd dist && node ../clean-build-artifacts.js
    - name: Copy build artifacts
      run: mv ./client/public/* ./dist/
    # - name: Publish build artifacts
    #   run: cd dist && git commit -a -m "${{ github.event.inputs.message }}" && git push
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        # Optional. Commit message for the created commit.
        # Defaults to "Apply automatic changes"
        commit_message: ${{ github.event.inputs.message }}

        # Optional. Local file path to the repository.
        # Defaults to the root of the repository.
        repository: ./dist
